name: Build and Deploy NPM Package
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - env:
          PKG_ACCESS_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}
        run:
          echo "//npm.pkg.github.com/:_authToken=${PKG_ACCESS_TOKEN}" >> ~/.npmrc
          yarn config set "@avarteqgmbh:registry" "https://npm.pkg.github.com"
          yarn install
      - env:
          PKG_ACCESS_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}
        run: yarn build
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}
        run: yarn publish
