name: Build and Deploy NPM Package
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
      - run:
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_ACCESS_TOKEN }}" >> ~/.npmrc
          yarn config set "@avarteqgmbh:registry" "https://npm.pkg.github.com"
          yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}
