name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        run: |
          yarn
          yarn check:types
          yarn lint
          yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
